version: "2"

linters:
  default: none
  enable:
    - asciicheck
    - bodyclose
    - dupl
    - err113
    - errcheck
    - errorlint
    - goconst
    - govet
    - ineffassign
    - staticcheck
    - unconvert
    - unused
    - unparam
    - nestif
    - revive
    - nilerr
    - nilnil
    - whitespace
    # - wsl
  settings:
    revive:
      rules:
        - name: var-naming
          disabled: true

severity:
  default: error
  rules:
    - linters:
        - unused
      severity: info
