Naming/AccessorMethodName:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Naming/VariableName:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/MethodCallWithoutArgsParentheses:
  Enabled: false
