Naming/AccessorMethodName:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Naming/VariableName:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/MethodCallWithoutArgsParentheses:
  Enabled: false

Style/StringConcatenation:
  Enabled: false

Layout/MultilineOperationIndentation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Layout/LineLength:
  Enabled: false
