version: "2"

linters:
  default: none
  enable:
    - asciicheck
    - bodyclose
    - dupl
    - errcheck
    - errorlint
    - goconst
    - govet
    - ineffassign
    - staticcheck
    - unconvert
    - unparam
    - nestif
    - revive
    - nilerr
    - nilnil
    - whitespace
    # - wsl
  settings:
    revive:
      rules:
        - name: var-naming
          disabled: true
    staticcheck:
      checks:
        - -SA9005
    unused:
      field-writes-are-uses: true
      post-statements-are-reads: false
      exported-fields-are-used: true
      parameters-are-used: true
      local-variables-are-used: true
      generated-is-used: true
  # exclusions:
  #   rules:
  #     - linters:
  #         - err113
  #         -

severity:
  default: error
  rules:
    - linters:
        # - ineffassign
        - httpresponse
      severity: info
